# Generated by Django 3.2.3 on 2021-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FilePathField(path='/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.FileField(upload_to='static'),
        ),
    ]
