# Generated by Django 3.2.3 on 2021-05-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210529_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='book',
        ),
    ]
