# Generated by Django 3.2.3 on 2021-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_post_comment_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.FileField(upload_to='books'),
        ),
    ]
