# Generated by Django 3.2.3 on 2021-05-31 00:37

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210530_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.FileField(upload_to='books', validators=[books.models.validate_file_extension]),
        ),
    ]
